<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kamera</name>
   <tag></tag>
   <elementGuidId>d34fa4e1-0d89-4aa1-8556-66ce911e69e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(1) > button:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Kamera&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4892580-658e-40f7-b038-9399722239e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kamera</value>
      <webElementGuid>1cc8dbfa-83f9-4d5f-b8dc-e9ad8cee93c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-919383dbd01a91ca11058c88ec800065</value>
      <webElementGuid>232a70f0-dcc9-4a39-8376-c8092d8f72f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 3)]</value>
      <webElementGuid>7675aac0-6928-490c-b2e0-839e8a9ac2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 3)]</value>
      <webElementGuid>8f8ab978-382e-4b0b-9442-c5494411f3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Kamera' or . = 'Kamera')]</value>
      <webElementGuid>7643a8c2-2d0a-45e1-9728-e1cb13b28736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
