<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>689731d5-a79c-4d76-a7d7-3bdb1443f695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'div') and (position() = 1)]/div/*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(1) > div > div:nth-child(1) > button:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b896accf-6fa4-487e-919b-21d757e30372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>2878e2e9-c127-4fa6-9558-1229eedfc40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-145a119d9b43ef8f7dc5229d22e400c7</value>
      <webElementGuid>c9b2634e-f029-462c-87fc-643862da31ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 1)]/div/*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 2)]</value>
      <webElementGuid>4daa5425-d5fc-434a-9996-fec8f3b44c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'div') and (position() = 1)]/div/*[(name() = 'div') and (position() = 1)]/*[(name() = 'button') and (position() = 2)]</value>
      <webElementGuid>192edb6c-6d61-468b-8045-2d5f4d049213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>4eb83457-db63-49d5-bd8e-7df1e6a2bcb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
