<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_https</name>
   <tag></tag>
   <elementGuidId>c5bfb733-734d-40a9-8d47-f4dc5075c667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@placeholder = 'https://...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[placeholder=&quot;https\:\/\/\.\.\.&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;https://...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cc81579-6e86-45e9-8118-4b342d1330a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://...</value>
      <webElementGuid>98ae218f-df12-42fe-b12c-6c81fc1fce16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a07c6df-8a1d-4f80-b735-7335371e6909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&amp;w=200</value>
      <webElementGuid>6e8c3912-426c-49d3-9047-1d6376486b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-93830db36381fa3f9b53ad41968815b4</value>
      <webElementGuid>4077ae95-003a-415b-a374-54bb82a53f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@placeholder = 'https://...']</value>
      <webElementGuid>42a7d960-1235-436f-b071-15238ecf6f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@placeholder = 'https://...']</value>
      <webElementGuid>214d715c-bf35-4aea-9a8e-b98ca45e2a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'https://...' and @type = 'text']</value>
      <webElementGuid>7cfaf780-1019-4def-bcef-9ef92d8ef1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
