<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Americano ID A1DCBE4E</name>
   <tag></tag>
   <elementGuidId>2ee9a577-4ed3-4d3f-acbd-a256f962a020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>Americano&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Americano Americano ID: A1DCBE4E&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a837b3c3-b46f-4c68-a85c-f02d95319941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Americano ID: A1DCBE4E</value>
      <webElementGuid>b7189c5e-52ff-41d8-a5b1-8fac89aec6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[2]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[1]/div[1]</value>
      <webElementGuid>d89ae97f-b656-43bd-8a52-5fde111a6377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/table/tbody/tr/td/div</value>
      <webElementGuid>ed8be28b-8063-4800-b900-969e5653afb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::div[1]</value>
      <webElementGuid>46bef33c-3557-4ad4-ac25-f98e67c4758f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATUS'])[1]/following::div[1]</value>
      <webElementGuid>39ff5dc2-c38e-44bd-8f93-919cc49692f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coffee'])[1]/preceding::div[2]</value>
      <webElementGuid>dc2685a8-700d-4c32-9e83-3a6bccdefd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>02ddb759-7110-49d2-9a94-0da714fed4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>Americano&#xd;
</value>
      <webElementGuid>03b552d8-8a2c-4aea-b9a3-63c0099af3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
